services:
  app:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
    ports:
      - '80:5173'
    environment:
      - NODE_ENV=development
    command: npm run dev